name: Verify PR

on:
  pull_request:
    branches: [ main ]

jobs:
  verify:

    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 14.x

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install yarn
        run: npm i yarn
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
